/* prettier-ignore */
/* eslint-disable */
// Generated by elegant-router
// Read more: https://github.com/mufeng889/elegant-router
// Vue auto route: https://github.com/soybeanjs/elegant-router
// 请不要手动修改此文件，否则会导致优雅路由无法正常工作
// 如果需要修改，请在优雅路由配置文件中进行修改
// 这是自动生成的文件，请不要手动修改

import '@soybean-react/vite-plugin-react-router';

declare module "@soybean-react/vite-plugin-react-router" {

  /**
   * route map
   */
  export type RouteMap = {
    "not-found": "*";
    "(base)_home": "/home";
    "(base)_manage": "/manage";
    "(base)_manage_cache": "/manage/cache";
    "(base)_manage_dept": "/manage/dept";
    "(base)_manage_dict": "/manage/dict";
    "(base)_manage_log": "/manage/log";
    "(base)_manage_menu": "/manage/menu";
    "(base)_manage_notice": "/manage/notice";
    "(base)_manage_online": "/manage/online";
    "(base)_manage_position": "/manage/position";
    "(base)_manage_resource": "/manage/resource";
    "(base)_manage_role": "/manage/role";
    "(base)_manage_role_[...slug]": "/manage/role/*";
    "(base)_manage_server": "/manage/server";
    "(base)_manage_user": "/manage/user";
    "(base)_manage_user_[id]": "/manage/user/:id";
    "(base)_user-center": "/user-center";
    "(blank)_login": "/login";
    "(blank)_login_code-login": "/login/code-login";
    "(blank)_login_register": "/login/register";
    "(blank)_login_reset-pwd": "/login/reset-pwd";
    "(blank)_login-out": "/login-out";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "iframe-page": "/iframe-page";
    "root": "/";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "not-found"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "(base)"
    | "(blank)"
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "root"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "not-found"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "(base)_home"
    | "(base)"
    | "(base)_manage_cache"
    | "(base)_manage_dept"
    | "(base)_manage_dict"
    | "(base)_manage"
    | "(base)_manage_log"
    | "(base)_manage_menu"
    | "(base)_manage_notice"
    | "(base)_manage_online"
    | "(base)_manage_position"
    | "(base)_manage_resource"
    | "(base)_manage_role_[...slug]"
    | "(base)_manage_role"
    | "(base)_manage_server"
    | "(base)_manage_user_[id]"
    | "(base)_manage_user"
    | "(base)_user-center"
    | "(blank)"
    | "(blank)_login-out"
    | "(blank)_login_code-login"
    | "(blank)_login"
    | "(blank)_login"
    | "(blank)_login_register"
    | "(blank)_login_reset-pwd"
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "root"
    | "root"
    | "root"
    | "root"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "not-found"
  >;
}
