/* prettier-ignore */
/* eslint-disable */
// Generated by elegant-router
// Read more: https://github.com/mufeng889/elegant-router
// Vue auto route: https://github.com/soybeanjs/elegant-router
// 请不要手动修改此文件，否则会导致优雅路由无法正常工作
// 如果需要修改，请在优雅路由配置文件中进行修改
// 这是自动生成的文件，请不要手动修改



export const layouts: Record<string, () => Promise<any>> = {
"(base)": () => import("@/pages/(base)/layout.tsx"),
"(blank)": () => import("@/pages/(blank)/layout.tsx"),
"(blank)_login": () => import("@/pages/(blank)/login/layout.tsx"),
"root": () => import("@/pages/layout.tsx"),
};

export const pages: Record<string, () => Promise<any>> = {
"(base)_home": () => import("@/pages/(base)/home/index.tsx"),
"(base)_manage_cache": () => import("@/pages/(base)/manage/cache/index.tsx"),
"(base)_manage_dept": () => import("@/pages/(base)/manage/dept/index.tsx"),
"(base)_manage_dict": () => import("@/pages/(base)/manage/dict/index.tsx"),
"(base)_manage": () => import("@/pages/(base)/manage/index.tsx"),
"(base)_manage_log": () => import("@/pages/(base)/manage/log/index.tsx"),
"(base)_manage_menu": () => import("@/pages/(base)/manage/menu/index.tsx"),
"(base)_manage_notice": () => import("@/pages/(base)/manage/notice/index.tsx"),
"(base)_manage_online": () => import("@/pages/(base)/manage/online/index.tsx"),
"(base)_manage_position": () => import("@/pages/(base)/manage/position/index.tsx"),
"(base)_manage_resource": () => import("@/pages/(base)/manage/resource/index.tsx"),
"(base)_manage_role_[...slug]": () => import("@/pages/(base)/manage/role/[...slug].tsx"),
"(base)_manage_role": () => import("@/pages/(base)/manage/role/index.tsx"),
"(base)_manage_server": () => import("@/pages/(base)/manage/server/index.tsx"),
"(base)_manage_user_[id]": () => import("@/pages/(base)/manage/user/[id].tsx"),
"(base)_manage_user": () => import("@/pages/(base)/manage/user/index.tsx"),
"(base)_user-center": () => import("@/pages/(base)/user-center/index.tsx"),
"(blank)_login-out": () => import("@/pages/(blank)/login-out/index.tsx"),
"(blank)_login_code-login": () => import("@/pages/(blank)/login/code-login/index.tsx"),
"(blank)_login": () => import("@/pages/(blank)/login/index.tsx"),
"(blank)_login_register": () => import("@/pages/(blank)/login/register/index.tsx"),
"(blank)_login_reset-pwd": () => import("@/pages/(blank)/login/reset-pwd/index.tsx"),
"403": () => import("@/pages/_builtin/403/index.tsx"),
"404": () => import("@/pages/_builtin/404/index.tsx"),
"500": () => import("@/pages/_builtin/500/index.tsx"),
"iframe-page": () => import("@/pages/_builtin/iframe-page/index.tsx"),
"root": () => import("@/pages/index.tsx"),
};

export const errors: Record<string, () => Promise<any>> = {
"root": () => import("@/pages/error.tsx"),
};