/* prettier-ignore */
/* eslint-disable */
// Generated by elegant-router
// Read more: https://github.com/mufeng889/elegant-router
// Vue auto route: https://github.com/soybeanjs/elegant-router
// 请不要手动修改此文件，否则会导致优雅路由无法正常工作
// 如果需要修改，请在优雅路由配置文件中进行修改
// 这是自动生成的文件，请不要手动修改

//这里只能修改 handle 并且路由组作为布局路由组件 是不能有handle的

import type { ElegantConstRoute } from '@soybean-react/vite-plugin-react-router';

export const generatedRoutes: ElegantConstRoute[] = [
  {
    matchedFiles: ['root', '/src/pages/index.tsx', '/src/pages/loading.tsx', 'root'],
    name: 'root',
    path: '/',
    handle: { i18nKey: 'route.root', title: 'root', constant: true },
    children: [
      {
        matchedFiles: ['(base)', null, null, null],
        name: '(base)',
        children: [
          {
            matchedFiles: [null, '/src/pages/(base)/home/index.tsx', null, null],
            name: '(base)_home',
            path: '/home',
            handle: { i18nKey: 'route.(base)_home', icon: 'mdi:monitor-dashboard', order: 1, title: 'home' }
          },
          {
            matchedFiles: [null, '/src/pages/(base)/manage/index.tsx', null, null],
            name: '(base)_manage',
            path: '/manage',
            handle: {
              i18nKey: 'route.(base)_manage',
              icon: 'carbon:cloud-service-management',
              order: 8,
              roles: ['R_ADMIN'],
              title: 'manage'
            },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/manage/cache/index.tsx', null, null],
                name: '(base)_manage_cache',
                path: '/manage/cache',
                handle: {
                  i18nKey: 'route.(base)_manage_cache',
                  icon: 'mdi:database',
                  order: 7,
                  roles: ['R_ADMIN'],
                  title: 'cache'
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/manage/dept/index.tsx', null, null],
                name: '(base)_manage_dept',
                path: '/manage/dept',
                handle: {
                  i18nKey: 'route.(base)_manage_dept',
                  icon: 'mdi:domain',
                  order: 5,
                  roles: ['R_ADMIN'],
                  title: 'dept'
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/manage/dict/index.tsx', null, null],
                name: '(base)_manage_dict',
                path: '/manage/dict',
                handle: {
                  i18nKey: 'route.(base)_manage_dict',
                  icon: 'mdi:book-alphabet',
                  order: 6,
                  roles: ['R_ADMIN'],
                  title: 'dict'
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/manage/log/index.tsx', null, null],
                name: '(base)_manage_log',
                path: '/manage/log',
                handle: {
                  i18nKey: 'route.(base)_manage_log',
                  icon: 'mdi:text-box-outline',
                  order: 9,
                  roles: ['R_ADMIN'],
                  title: 'log'
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/manage/menu/index.tsx', null, null],
                name: '(base)_manage_menu',
                path: '/manage/menu',
                handle: {
                  i18nKey: 'route.(base)_manage_menu',
                  title: 'Manage Menu',
                  icon: 'material-symbols:route',
                  order: 3,
                  roles: ['R_SUPER']
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/manage/notice/index.tsx', null, null],
                name: '(base)_manage_notice',
                path: '/manage/notice',
                handle: {
                  i18nKey: 'route.(base)_manage_notice',
                  icon: 'mdi:bullhorn-outline',
                  order: 10,
                  roles: ['R_ADMIN'],
                  title: 'notice'
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/manage/online/index.tsx', null, null],
                name: '(base)_manage_online',
                path: '/manage/online',
                handle: {
                  i18nKey: 'route.(base)_manage_online',
                  icon: 'mdi:account-group',
                  order: 8,
                  roles: ['R_ADMIN'],
                  title: 'online'
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/manage/position/index.tsx', null, null],
                name: '(base)_manage_position',
                path: '/manage/position',
                handle: {
                  i18nKey: 'route.(base)_manage_position',
                  icon: 'mdi:briefcase-outline',
                  order: 4,
                  roles: ['R_ADMIN'],
                  title: 'position'
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/manage/resource/index.tsx', null, null],
                name: '(base)_manage_resource',
                path: '/manage/resource',
                handle: {
                  i18nKey: 'route.(base)_manage_resource',
                  icon: 'mdi:folder-outline',
                  order: 11,
                  roles: ['R_ADMIN'],
                  title: 'resource'
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/manage/role/index.tsx', null, null],
                name: '(base)_manage_role',
                path: '/manage/role',
                handle: {
                  i18nKey: 'route.(base)_manage_role',
                  icon: 'carbon:user-role',
                  order: 2,
                  roles: ['R_SUPER'],
                  title: 'manage_role'
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/manage/role/[...slug].tsx', null, null],
                    name: '(base)_manage_role_[...slug]',
                    path: '/manage/role/*',
                    handle: {
                      i18nKey: 'route.(base)_manage_role_[...slug]',
                      hideInMenu: true,
                      activeMenu: '/manage/role',
                      title: '(base)_manage_role_[...slug]'
                    }
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/manage/server/index.tsx', null, null],
                name: '(base)_manage_server',
                path: '/manage/server',
                handle: {
                  i18nKey: 'route.(base)_manage_server',
                  icon: 'mdi:server',
                  order: 12,
                  roles: ['R_ADMIN'],
                  title: 'server'
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/manage/user/index.tsx', null, null],
                name: '(base)_manage_user',
                path: '/manage/user',
                handle: {
                  i18nKey: 'route.(base)_manage_user',
                  icon: 'ic:round-manage-accounts',
                  keepAlive: true,
                  order: 1,
                  roles: ['R_ADMIN'],
                  title: 'manage_user'
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/manage/user/[id].tsx', null, null],
                    name: '(base)_manage_user_[id]',
                    path: '/manage/user/:id',
                    handle: {
                      activeMenu: '/manage/user',
                      hideInMenu: true,
                      i18nKey: 'route.(base)_manage_user_[id]',
                      title: '(base)_manage_user_[id]'
                    }
                  }
                ]
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/user-center/index.tsx', null, null],
            name: '(base)_user-center',
            path: '/user-center',
            handle: { hideInMenu: true, i18nKey: 'route.(base)_user-center', title: 'user-center' }
          }
        ],
        path: null
      },
      {
        matchedFiles: ['(blank)', null, null, null],
        name: '(blank)',
        children: [
          {
            matchedFiles: ['(blank)_login', '/src/pages/(blank)/login/index.tsx', null, null],
            name: '(blank)_login',
            path: '/login',
            handle: { i18nKey: 'route.(blank)_login', title: '(blank)_login', constant: true },
            children: [
              {
                matchedFiles: [null, '/src/pages/(blank)/login/code-login/index.tsx', null, null],
                name: '(blank)_login_code-login',
                path: '/login/code-login',
                handle: { i18nKey: 'route.(blank)_login_code-login', title: '(blank)_login_code-login', constant: true }
              },
              {
                matchedFiles: [null, '/src/pages/(blank)/login/register/index.tsx', null, null],
                name: '(blank)_login_register',
                path: '/login/register',
                handle: { i18nKey: 'route.(blank)_login_register', title: '(blank)_login_register', constant: true }
              },
              {
                matchedFiles: [null, '/src/pages/(blank)/login/reset-pwd/index.tsx', null, null],
                name: '(blank)_login_reset-pwd',
                path: '/login/reset-pwd',
                handle: { i18nKey: 'route.(blank)_login_reset-pwd', title: '(blank)_login_reset-pwd', constant: true }
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(blank)/login-out/index.tsx', null, null],
            name: '(blank)_login-out',
            path: '/login-out',
            handle: { i18nKey: 'route.(blank)_login-out', title: '(blank)_login-out', constant: true }
          }
        ],
        path: null
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/403/index.tsx', null, null],
        name: '403',
        path: '/403',
        handle: { i18nKey: 'route.403', title: '403', constant: true }
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/404/index.tsx', null, null],
        name: '404',
        path: '/404',
        handle: { i18nKey: 'route.404', title: '404', constant: true }
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/500/index.tsx', null, null],
        name: '500',
        path: '/500',
        handle: { i18nKey: 'route.500', title: '500', constant: true }
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/iframe-page/index.tsx', null, null],
        name: 'iframe-page',
        path: '/iframe-page',
        handle: { i18nKey: 'route.iframe-page', title: 'iframe-page', constant: true }
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/404/index.tsx', null, null],
        name: 'notFound',
        path: '*',
        handle: { i18nKey: 'route.notFound', title: 'notFound', constant: true }
      }
    ]
  }
];
