/* prettier-ignore */
/* eslint-disable */
// Generated by elegant-router
// Read more: https://github.com/mufeng889/elegant-router
// Vue auto route: https://github.com/soybeanjs/elegant-router
// 请不要手动修改此文件，否则会导致优雅路由无法正常工作
// 如果需要修改，请在优雅路由配置文件中进行修改
// 这是自动生成的文件，请不要手动修改


import type { RouteKey, RouteMap, RoutePath } from '@soybean-react/vite-plugin-react-router';

/**
* map of route name and route path
*/
export const routeMap: RouteMap = {
 "not-found": "*",
 "(base)_home": "/home",
 "(base)_manage": "/manage",
 "(base)_manage_cache": "/manage/cache",
 "(base)_manage_dept": "/manage/dept",
 "(base)_manage_dict": "/manage/dict",
 "(base)_manage_log": "/manage/log",
 "(base)_manage_menu": "/manage/menu",
 "(base)_manage_notice": "/manage/notice",
 "(base)_manage_online": "/manage/online",
 "(base)_manage_position": "/manage/position",
 "(base)_manage_resource": "/manage/resource",
 "(base)_manage_role": "/manage/role",
 "(base)_manage_role_[...slug]": "/manage/role/*",
 "(base)_manage_server": "/manage/server",
 "(base)_manage_user": "/manage/user",
 "(base)_manage_user_[id]": "/manage/user/:id",
 "(base)_user-center": "/user-center",
 "(blank)_login": "/login",
 "(blank)_login_code-login": "/login/code-login",
 "(blank)_login_register": "/login/register",
 "(blank)_login_reset-pwd": "/login/reset-pwd",
 "(blank)_login-out": "/login-out",
 "403": "/403",
 "404": "/404",
 "500": "/500",
 "iframe-page": "/iframe-page",
 "root": "/"
};

/**
* get route path by route name
*
* @param name route name
*/
export function getRoutePath<T extends RouteKey>(name: T) {
 return routeMap[name];
}

/**
* get route name by route path
*
* @param path route path
*/
export function getRouteName(path: RoutePath) {
 const routeEntries = Object.entries(routeMap) as [RouteKey, RoutePath][];

 const routeName: RouteKey | null = routeEntries.find(([, routePath]) => routePath === path)?.[0] || null;

 return routeName;
}