/** 系统管理 / 监控模块 API（对接 FastAPI /api/v1） */

const API_PREFIX = '/api/v1';

export const SYSTEM_MODULE_URLS = {
  USER_LIST: `${API_PREFIX}/system/user/list`,
  USER_CURRENT_INFO: `${API_PREFIX}/system/user/current/info`,
  USER_CURRENT_UPDATE: `${API_PREFIX}/system/user/current/info/update`,
  USER_CURRENT_AVATAR_UPLOAD: `${API_PREFIX}/system/user/current/avatar/upload`,
  USER_CURRENT_PASSWORD_CHANGE: `${API_PREFIX}/system/user/current/password/change`,
  USER_DETAIL: (id: number) => `${API_PREFIX}/system/user/detail/${id}`,
  USER_CREATE: `${API_PREFIX}/system/user/create`,
  USER_UPDATE: (id: number) => `${API_PREFIX}/system/user/update/${id}`,
  USER_DELETE: `${API_PREFIX}/system/user/delete`,
  USER_BATCH_STATUS: `${API_PREFIX}/system/user/available/setting`,
  ROLE_LIST: `${API_PREFIX}/system/role/list`,
  ROLE_DETAIL: (id: number) => `${API_PREFIX}/system/role/detail/${id}`,
  ROLE_CREATE: `${API_PREFIX}/system/role/create`,
  ROLE_UPDATE: (id: number) => `${API_PREFIX}/system/role/update/${id}`,
  ROLE_DELETE: `${API_PREFIX}/system/role/delete`,
  ROLE_BATCH_STATUS: `${API_PREFIX}/system/role/available/setting`,
  ROLE_PERMISSION: `${API_PREFIX}/system/role/permission/setting`,
  MENU_TREE: `${API_PREFIX}/system/menu/tree`,
  POSITION_LIST: `${API_PREFIX}/system/position/list`,
  POSITION_DETAIL: (id: number) => `${API_PREFIX}/system/position/detail/${id}`,
  POSITION_CREATE: `${API_PREFIX}/system/position/create`,
  POSITION_UPDATE: (id: number) => `${API_PREFIX}/system/position/update/${id}`,
  POSITION_DELETE: `${API_PREFIX}/system/position/delete`,
  POSITION_BATCH_STATUS: `${API_PREFIX}/system/position/available/setting`,
  DEPT_TREE: `${API_PREFIX}/system/dept/tree`,
  DEPT_DETAIL: (id: number) => `${API_PREFIX}/system/dept/detail/${id}`,
  DEPT_CREATE: `${API_PREFIX}/system/dept/create`,
  DEPT_UPDATE: (id: number) => `${API_PREFIX}/system/dept/update/${id}`,
  DEPT_DELETE: `${API_PREFIX}/system/dept/delete`,
  DEPT_BATCH_STATUS: `${API_PREFIX}/system/dept/available/setting`,
  DICT_TYPE_LIST: `${API_PREFIX}/system/dict/type/list`,
  DICT_TYPE_OPTION: `${API_PREFIX}/system/dict/type/optionselect`,
  DICT_TYPE_DETAIL: (id: number) => `${API_PREFIX}/system/dict/type/detail/${id}`,
  DICT_TYPE_CREATE: `${API_PREFIX}/system/dict/type/create`,
  DICT_TYPE_UPDATE: (id: number) => `${API_PREFIX}/system/dict/type/update/${id}`,
  DICT_TYPE_DELETE: `${API_PREFIX}/system/dict/type/delete`,
  DICT_TYPE_BATCH_STATUS: `${API_PREFIX}/system/dict/type/available/setting`,
  DICT_DATA_LIST: `${API_PREFIX}/system/dict/data/list`,
  DICT_DATA_DETAIL: (id: number) => `${API_PREFIX}/system/dict/data/detail/${id}`,
  DICT_DATA_CREATE: `${API_PREFIX}/system/dict/data/create`,
  DICT_DATA_UPDATE: (id: number) => `${API_PREFIX}/system/dict/data/update/${id}`,
  DICT_DATA_DELETE: `${API_PREFIX}/system/dict/data/delete`,
  DICT_DATA_BATCH_STATUS: `${API_PREFIX}/system/dict/data/available/setting`,
  LOG_LIST: `${API_PREFIX}/system/log/list`,
  LOG_DETAIL: (id: number) => `${API_PREFIX}/system/log/detail/${id}`,
  LOG_DELETE: `${API_PREFIX}/system/log/delete`,
  NOTICE_LIST: `${API_PREFIX}/system/notice/list`,
  NOTICE_DETAIL: (id: number) => `${API_PREFIX}/system/notice/detail/${id}`,
  NOTICE_CREATE: `${API_PREFIX}/system/notice/create`,
  NOTICE_UPDATE: (id: number) => `${API_PREFIX}/system/notice/update/${id}`,
  NOTICE_DELETE: `${API_PREFIX}/system/notice/delete`,
  NOTICE_BATCH_STATUS: `${API_PREFIX}/system/notice/available/setting`,
  NOTICE_AVAILABLE: `${API_PREFIX}/system/notice/available`,
  RESOURCE_LIST: `${API_PREFIX}/monitor/resource/list`,
  RESOURCE_UPLOAD: `${API_PREFIX}/monitor/resource/upload`,
  RESOURCE_DOWNLOAD: `${API_PREFIX}/monitor/resource/download`,
  RESOURCE_DELETE: `${API_PREFIX}/monitor/resource/delete`,
  RESOURCE_MOVE: `${API_PREFIX}/monitor/resource/move`,
  RESOURCE_COPY: `${API_PREFIX}/monitor/resource/copy`,
  RESOURCE_RENAME: `${API_PREFIX}/monitor/resource/rename`,
  RESOURCE_CREATE_DIR: `${API_PREFIX}/monitor/resource/create-dir`,
  RESOURCE_EXPORT: `${API_PREFIX}/monitor/resource/export`,
  CACHE_INFO: `${API_PREFIX}/monitor/cache/info`,
  CACHE_NAMES: `${API_PREFIX}/monitor/cache/get/names`,
  CACHE_KEYS: (cacheName: string) => `${API_PREFIX}/monitor/cache/get/keys/${encodeURIComponent(cacheName)}`,
  CACHE_VALUE: (cacheName: string, cacheKey: string) =>
    `${API_PREFIX}/monitor/cache/get/value/${encodeURIComponent(cacheName)}/${encodeURIComponent(cacheKey)}`,
  CACHE_DELETE_NAME: (cacheName: string) => `${API_PREFIX}/monitor/cache/delete/name/${encodeURIComponent(cacheName)}`,
  CACHE_DELETE_KEY: (cacheKey: string) => `${API_PREFIX}/monitor/cache/delete/key/${encodeURIComponent(cacheKey)}`,
  CACHE_DELETE_ALL: `${API_PREFIX}/monitor/cache/delete/all`,
  ONLINE_LIST: `${API_PREFIX}/monitor/online/list`,
  ONLINE_DELETE: `${API_PREFIX}/monitor/online/delete`,
  ONLINE_CLEAR: `${API_PREFIX}/monitor/online/clear`,
  SERVER_INFO: `${API_PREFIX}/monitor/server/info`
} as const;
